In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('C:\\Users\\krishna\\AppData\\Local\\Temp\\Temp1_graduate-admissions.zip\\Admission_Predict.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

In [4]:
df1=df.set_index('Serial No.')
df1

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
Serial No.                                                               
1                 337          118                  4  4.5   4.5  9.65   
2                 324          107                  4  4.0   4.5  8.87   
3                 316          104                  3  3.0   3.5  8.00   
4                 322          110                  3  3.5   2.5  8.67   
5                 314          103                  2  2.0   3.0  8.21   
...               ...          ...                ...  ...   ...   ...   
396               324          110                  3  3.5   3.5  9.04   
397               325          107                  3  3.0   3.5  9.11   
398               330          116                  4  5.0   4.5  9.45   
399               312          103                  3  3.5   4.0  8.78   
400               333          117                  4  5.0   4.0  9.66   

            Research  Chance of Admit   
Serial No.                              
1                  1              0.92  
2                  1              0.76  
3                  1              0.72  
4                  1              0.80  
5                  0              0.65  
...              ...               ...  
396                1              0.82  
397                1              0.84  
398                1              0.91  
399                0              0.67  
400                1              0.95  

[400 rows x 8 columns]

In [5]:
x=df1.iloc[:,:-1].values

In [6]:
y=df1.iloc[:,-1].values

In [14]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x1=ss.fit_transform(x)
x1

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [20]:
scaled_frame=pd.DataFrame(data=x1,columns=('GRE Score','TOEFL Score','University Rating','SOP','LOR','CGPA','Research'))
scaled_frame

GRE Score  TOEFL Score  University Rating       SOP       LOR      CGPA  \
0     1.762107     1.746971           0.798829  1.093864  1.167321  1.764818   
1     0.627656    -0.067635           0.798829  0.596653  1.167321  0.455151   
2    -0.070467    -0.562528          -0.076600 -0.397769  0.052933 -1.005631   
3     0.453126     0.427257          -0.076600  0.099442 -1.061454  0.119339   
4    -0.244998    -0.727492          -0.952029 -1.392191 -0.504260 -0.653029   
..         ...          ...                ...       ...       ...       ...   
395   0.627656     0.427257          -0.076600  0.099442  0.052933  0.740592   
396   0.714922    -0.067635          -0.076600 -0.397769  0.052933  0.858126   
397   1.151249     1.417042           0.798829  1.591075  1.167321  1.429006   
398  -0.419528    -0.727492          -0.076600  0.099442  0.610127  0.304036   
399   1.413045     1.582006           0.798829  1.591075  0.610127  1.781609   

     Research  
0    0.909112  
1    0.909112  
2    0.909112  
3    0.909112  
4   -1.099975  
..        ...  
395  0.909112  
396  0.909112  
397  0.909112  
398 -1.099975  
399  0.909112  

[400 rows x 7 columns]

In [16]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y_train,y_test=train_test_split(x1,y,test_size=0.25,random_state=0)

In [17]:
from sklearn.tree import DecisionTreeRegressor
DTR=DecisionTreeRegressor()
DTR.fit(x1_train,y_train)
pred=DTR.predict(x1_test)
pred

array([0.77, 0.45, 0.79, 0.67, 0.77, 0.64, 0.76, 0.64, 0.93, 0.91, 0.56,
       0.91, 0.65, 0.36, 0.83, 0.72, 0.73, 0.86, 0.65, 0.76, 0.89, 0.86,
       0.71, 0.46, 0.87, 0.65, 0.46, 0.62, 0.87, 0.57, 0.69, 0.71, 0.69,
       0.63, 0.8 , 0.8 , 0.65, 0.86, 0.53, 0.94, 0.71, 0.69, 0.78, 0.84,
       0.83, 0.65, 0.58, 0.64, 0.72, 0.64, 0.66, 0.84, 0.73, 0.83, 0.68,
       0.7 , 0.65, 0.73, 0.76, 0.79, 0.82, 0.47, 0.53, 0.38, 0.78, 0.85,
       0.57, 0.92, 0.84, 0.73, 0.46, 0.84, 0.91, 0.65, 0.91, 0.73, 0.59,
       0.53, 0.9 , 0.49, 0.63, 0.73, 0.65, 0.89, 0.56, 0.78, 0.73, 0.71,
       0.81, 0.8 , 0.7 , 0.92, 0.49, 0.56, 0.82, 0.7 , 0.69, 0.53, 0.73,
       0.79])

In [18]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
from numpy import sqrt
rmse=sqrt(mean_squared_error(pred,y_test))
rmse

0.10090589675534328

In [19]:
from sklearn.metrics import r2_score
r2score=r2_score(pred,y_test)
accuracy=r2score*100
accuracy

43.2548698991662

In [25]:
from sklearn.ensemble import RandomForestRegressor
RFR=RandomForestRegressor()
RFR.fit(x1_train,y_train)
Rpred=RFR.predict(x1_test)
Rpred

C:\Users\krishna\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([0.714, 0.609, 0.781, 0.668, 0.769, 0.619, 0.751, 0.652, 0.922,
       0.917, 0.528, 0.907, 0.661, 0.499, 0.836, 0.66 , 0.675, 0.832,
       0.571, 0.722, 0.845, 0.857, 0.666, 0.446, 0.832, 0.579, 0.434,
       0.68 , 0.861, 0.659, 0.59 , 0.743, 0.742, 0.524, 0.786, 0.769,
       0.641, 0.91 , 0.59 , 0.936, 0.737, 0.683, 0.738, 0.814, 0.797,
       0.672, 0.531, 0.667, 0.631, 0.566, 0.68 , 0.796, 0.679, 0.863,
       0.686, 0.718, 0.661, 0.741, 0.773, 0.838, 0.756, 0.498, 0.662,
       0.479, 0.835, 0.891, 0.663, 0.902, 0.783, 0.761, 0.612, 0.839,
       0.845, 0.592, 0.918, 0.645, 0.651, 0.642, 0.925, 0.473, 0.711,
       0.738, 0.618, 0.853, 0.575, 0.802, 0.702, 0.74 , 0.788, 0.793,
       0.758, 0.936, 0.562, 0.539, 0.824, 0.665, 0.758, 0.683, 0.736,
       0.739])

In [26]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
from numpy import sqrt
rmse=sqrt(mean_squared_error(Rpred,y_test))
rmse

0.07473780837032885

In [27]:
from sklearn.metrics import r2_score
r2score=r2_score(Rpred,y_test)
accuracy=r2score*100
accuracy

61.66043810829481