In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('C:\\Users\\krishna\\Downloads\\parkinsons2.csv')
df

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0        119.992       157.302        74.997         0.00784   
1        122.400       148.650       113.819         0.00968   
2        116.682       131.111       111.555         0.01050   
3        116.676       137.871       111.366         0.00997   
4        116.014       141.781       110.655         0.01284   
..           ...           ...           ...             ...   
190      174.188       230.978        94.261         0.00459   
191      209.516       253.017        89.488         0.00564   
192      174.688       240.005        74.287         0.01360   
193      198.764       396.961        74.904         0.00740   
194      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0             0.00007   0.00370   0.00554     0.01109       0.04374   
1             0.00008   0.00465   0.00696     0.01394       0.06134   
2             0.00009   0.00544   0.00781     0.01633       0.05233   
3             0.00009   0.00502   0.00698     0.01505       0.05492   
4             0.00011   0.00655   0.00908     0.01966       0.06425   
..                ...       ...       ...         ...           ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087   
191           0.00003   0.00331   0.00292     0.00994       0.02751   
192           0.00008   0.00624   0.00564     0.01873       0.02308   
193           0.00004   0.00370   0.00390     0.01109       0.02296   
194           0.00003   0.00295   0.00317     0.00885       0.01884   

     MDVP:Shimmer(dB)  ...  Shimmer:DDA      NHR     HNR      RPDE       DFA  \
0               0.426  ...      0.06545  0.02211  21.033  0.414783  0.815285   
1               0.626  ...      0.09403  0.01929  19.085  0.458359  0.819521   
2               0.482  ...      0.08270  0.01309  20.651  0.429895  0.825288   
3               0.517  ...      0.08771  0.01353  20.644  0.434969  0.819235   
4               0.584  ...      0.10470  0.01767  19.649  0.417356  0.823484   
..                ...  ...          ...      ...     ...       ...       ...   
190             0.405  ...      0.07008  0.02764  19.517  0.448439  0.657899   
191             0.263  ...      0.04812  0.01810  19.147  0.431674  0.683244   
192             0.256  ...      0.03804  0.10715  17.883  0.407567  0.655683   
193             0.241  ...      0.03794  0.07223  19.020  0.451221  0.643956   
194             0.190  ...      0.03078  0.04398  21.209  0.462803  0.664357   

      spread1   spread2        D2       PPE  status  
0   -4.813031  0.266482  2.301442  0.284654       1  
1   -4.075192  0.335590  2.486855  0.368674       1  
2   -4.443179  0.311173  2.342259  0.332634       1  
3   -4.117501  0.334147  2.405554  0.368975       1  
4   -3.747787  0.234513  2.332180  0.410335       1  
..        ...       ...       ...       ...     ...  
190 -6.538586  0.121952  2.657476  0.133050       0  
191 -6.195325  0.129303  2.784312  0.168895       0  
192 -6.787197  0.158453  2.679772  0.131728       0  
193 -6.744577  0.207454  2.138608  0.123306       0  
194 -5.724056  0.190667  2.555477  0.148569       0  

[195 rows x 23 columns]

In [3]:
x=df.iloc[:,:-1].values

In [5]:
y=df.iloc[:,-1].values

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x1_train=ss.fit_transform(x_train)
x1_test=ss.transform(x_test)

In [18]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x1_train,y_train)
pred=dt.predict(x1_test)
pred

array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1], dtype=int64)

In [9]:
from sklearn.metrics import *

In [10]:
from numpy import sqrt

In [19]:
confusion=confusion_matrix(y_test,pred)
confusion

array([[ 9,  2],
       [ 2, 36]], dtype=int64)

In [20]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.82      0.82      0.82        11
           1       0.95      0.95      0.95        38

    accuracy                           0.92        49
   macro avg       0.88      0.88      0.88        49
weighted avg       0.92      0.92      0.92        49



In [21]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x1_train,y_train)
pred2=rfc.predict(x1_test)
pred2

C:\Users\krishna\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1], dtype=int64)

In [22]:
confusion2=confusion_matrix(y_test,pred2)
confusion2

array([[11,  0],
       [ 2, 36]], dtype=int64)

In [23]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       0.85      1.00      0.92        11
           1       1.00      0.95      0.97        38

    accuracy                           0.96        49
   macro avg       0.92      0.97      0.94        49
weighted avg       0.97      0.96      0.96        49

