In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('C:\\Users\\krishna\\AppData\\Local\\Temp\\Temp1_15953_21070_bundle_archive.zip\\train_u6lujuX_CVtuZ9i (1).csv')
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [3]:
dff=pd.DataFrame(data=df,columns=['Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area','Loan_Status'])
dff.head()

Self_Employed  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0            No             5849                0.0         NaN   
1            No             4583             1508.0       128.0   
2           Yes             3000                0.0        66.0   
3            No             2583             2358.0       120.0   
4            No             6000                0.0       141.0   

   Loan_Amount_Term  Credit_History Property_Area Loan_Status  
0             360.0             1.0         Urban           Y  
1             360.0             1.0         Rural           N  
2             360.0             1.0         Urban           Y  
3             360.0             1.0         Urban           Y  
4             360.0             1.0         Urban           Y

In [4]:
dff.isnull().any()

Self_Employed         True
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount            True
Loan_Amount_Term      True
Credit_History        True
Property_Area        False
Loan_Status          False
dtype: bool

In [5]:
dff=dff.fillna(np.mean(dff))
dff

Self_Employed  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0              No             5849                0.0  146.412162   
1              No             4583             1508.0  128.000000   
2             Yes             3000                0.0   66.000000   
3              No             2583             2358.0  120.000000   
4              No             6000                0.0  141.000000   
..            ...              ...                ...         ...   
609            No             2900                0.0   71.000000   
610            No             4106                0.0   40.000000   
611            No             8072              240.0  253.000000   
612            No             7583                0.0  187.000000   
613           Yes             4583                0.0  133.000000   

     Loan_Amount_Term  Credit_History Property_Area Loan_Status  
0               360.0             1.0         Urban           Y  
1               360.0             1.0         Rural           N  
2               360.0             1.0         Urban           Y  
3               360.0             1.0         Urban           Y  
4               360.0             1.0         Urban           Y  
..                ...             ...           ...         ...  
609             360.0             1.0         Rural           Y  
610             180.0             1.0         Rural           Y  
611             360.0             1.0         Urban           Y  
612             360.0             1.0         Urban           Y  
613             360.0             0.0     Semiurban           N  

[614 rows x 8 columns]

In [6]:
dff.isnull().any()

Self_Employed         True
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount           False
Loan_Amount_Term     False
Credit_History       False
Property_Area        False
Loan_Status          False
dtype: bool

In [7]:
del dff['Self_Employed']

In [36]:
del dff['Property_Area']

In [37]:
dff.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Loan_Status  
0             1.0           Y  
1             1.0           N  
2             1.0           Y  
3             1.0           Y  
4             1.0           Y

In [38]:
x=dff.iloc[:,:-1].values

In [50]:
x.shape

(614, 5)

In [39]:
y=dff.iloc[:,-1].values

In [40]:
from sklearn.preprocessing import LabelEncoder

In [53]:
l=LabelEncoder()
y1=l.fit_transform(y)
y1=y1.reshape(-1,1)

In [54]:
y1.shape

(614, 1)

In [55]:
dff=np.hstack([x,y1])
dff

array([[5.84900000e+03, 0.00000000e+00, 1.46412162e+02, 3.60000000e+02,
        1.00000000e+00, 1.00000000e+00],
       [4.58300000e+03, 1.50800000e+03, 1.28000000e+02, 3.60000000e+02,
        1.00000000e+00, 0.00000000e+00],
       [3.00000000e+03, 0.00000000e+00, 6.60000000e+01, 3.60000000e+02,
        1.00000000e+00, 1.00000000e+00],
       ...,
       [8.07200000e+03, 2.40000000e+02, 2.53000000e+02, 3.60000000e+02,
        1.00000000e+00, 1.00000000e+00],
       [7.58300000e+03, 0.00000000e+00, 1.87000000e+02, 3.60000000e+02,
        1.00000000e+00, 1.00000000e+00],
       [4.58300000e+03, 0.00000000e+00, 1.33000000e+02, 3.60000000e+02,
        0.00000000e+00, 0.00000000e+00]])

In [58]:
dff.shape

(614, 6)

In [59]:
dff=pd.DataFrame(data=dff,columns=['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Loan_Status'])
dff.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0           5849.0                0.0  146.412162             360.0   
1           4583.0             1508.0  128.000000             360.0   
2           3000.0                0.0   66.000000             360.0   
3           2583.0             2358.0  120.000000             360.0   
4           6000.0                0.0  141.000000             360.0   

   Credit_History  Loan_Status  
0             1.0          1.0  
1             1.0          0.0  
2             1.0          1.0  
3             1.0          1.0  
4             1.0          1.0

In [60]:
x=dff.iloc[:,:-1].values

In [61]:
y=dff.iloc[:,-1].values

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [63]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
pred=lr.predict(x_test)

C:\Users\krishna\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [64]:
from sklearn.metrics import *

In [65]:
cf=confusion_matrix(y_test,pred)
cf

array([[ 20,  23],
       [  2, 109]], dtype=int64)

In [66]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

         0.0       0.91      0.47      0.62        43
         1.0       0.83      0.98      0.90       111

    accuracy                           0.84       154
   macro avg       0.87      0.72      0.76       154
weighted avg       0.85      0.84      0.82       154



In [67]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)
predn=nb.predict(x_test)

In [68]:
cf=confusion_matrix(y_test,predn)
cf

array([[ 20,  23],
       [  4, 107]], dtype=int64)

In [69]:
print(classification_report(y_test,predn))

              precision    recall  f1-score   support

         0.0       0.83      0.47      0.60        43
         1.0       0.82      0.96      0.89       111

    accuracy                           0.82       154
   macro avg       0.83      0.71      0.74       154
weighted avg       0.83      0.82      0.81       154



In [70]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
predt=dt.predict(x_test)

In [71]:
cf=confusion_matrix(y_test,predt)
cf

array([[24, 19],
       [25, 86]], dtype=int64)

In [72]:
print(classification_report(y_test,predt))

              precision    recall  f1-score   support

         0.0       0.49      0.56      0.52        43
         1.0       0.82      0.77      0.80       111

    accuracy                           0.71       154
   macro avg       0.65      0.67      0.66       154
weighted avg       0.73      0.71      0.72       154



In [73]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x1_train=ss.fit_transform(x_train)
x1_test=ss.transform(x_test)

In [74]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

In [75]:
for k in range(1,11):
    knn=KNeighborsClassifier(k)
    knn.fit(x1_train,y_train)
    predk=knn.predict(x1_test)
    accuracy=accuracy_score(y_test,predk)
    print('accuracy of k=',k,'is',accuracy)

accuracy of k= 1 is 0.7337662337662337
accuracy of k= 2 is 0.7012987012987013
accuracy of k= 3 is 0.7792207792207793
accuracy of k= 4 is 0.7727272727272727
accuracy of k= 5 is 0.8051948051948052
accuracy of k= 6 is 0.7922077922077922
accuracy of k= 7 is 0.8116883116883117
accuracy of k= 8 is 0.8116883116883117
accuracy of k= 9 is 0.8246753246753247
accuracy of k= 10 is 0.8311688311688312


In [77]:
knn=KNeighborsClassifier(2)
knn.fit(x1_train,y_train)
predk1=knn.predict(x1_test)

In [78]:
cf=confusion_matrix(y_test,predk1)
cf

array([[28, 15],
       [31, 80]], dtype=int64)

In [79]:
print(classification_report(y_test,predk1))

              precision    recall  f1-score   support

         0.0       0.47      0.65      0.55        43
         1.0       0.84      0.72      0.78       111

    accuracy                           0.70       154
   macro avg       0.66      0.69      0.66       154
weighted avg       0.74      0.70      0.71       154



In [80]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier()
gbc.fit(x_train,y_train)
predg=gbc.predict(x_test)

In [81]:
cf=confusion_matrix(y_test,predg)
cf

array([[ 19,  24],
       [  5, 106]], dtype=int64)

In [82]:
print(classification_report(y_test,predg))

              precision    recall  f1-score   support

         0.0       0.79      0.44      0.57        43
         1.0       0.82      0.95      0.88       111

    accuracy                           0.81       154
   macro avg       0.80      0.70      0.72       154
weighted avg       0.81      0.81      0.79       154

