In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('C:\\Users\\krishna\\AppData\\Local\\Temp\\Temp1_breast-cancer-prediction-dataset.zip\\Breast_cancer_data.csv')
df.head()

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   diagnosis  
0          0  
1          0  
2          0  
3          0  
4          0

In [4]:
x=df.iloc[:,:-1].values

In [5]:
y=df.iloc[:,-1].values

In [11]:
from sklearn.metrics import *

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x1_train=ss.fit_transform(x_train)
x1_test=ss.transform(x_test)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x1_train,y_train)
pred=knn.predict(x1_test)
pred

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0], dtype=int64)

In [13]:
for k in range(20):
    k=k+1
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x1_train,y_train)
    pred1=knn.predict(x1_test)
    accuracy=accuracy_score(y_test,pred1)
    print('accuracy for k',k,'is',accuracy)

accuracy for k 1 is 0.8951048951048951
accuracy for k 2 is 0.8461538461538461
accuracy for k 3 is 0.8951048951048951
accuracy for k 4 is 0.8741258741258742
accuracy for k 5 is 0.8881118881118881
accuracy for k 6 is 0.8881118881118881
accuracy for k 7 is 0.8881118881118881
accuracy for k 8 is 0.8811188811188811
accuracy for k 9 is 0.9020979020979021
accuracy for k 10 is 0.9020979020979021
accuracy for k 11 is 0.916083916083916
accuracy for k 12 is 0.9230769230769231
accuracy for k 13 is 0.916083916083916
accuracy for k 14 is 0.9300699300699301
accuracy for k 15 is 0.9230769230769231
accuracy for k 16 is 0.9230769230769231
accuracy for k 17 is 0.9300699300699301
accuracy for k 18 is 0.9300699300699301
accuracy for k 19 is 0.9300699300699301
accuracy for k 20 is 0.9300699300699301


In [16]:
knn=KNeighborsClassifier(2)
knn.fit(x1_train,y_train)
final_pred=knn.predict(x1_test)
final_pred

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [17]:
confusion=confusion_matrix(y_test,pred1)
confusion

array([[47,  6],
       [ 4, 86]], dtype=int64)