In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('C:\\Users\\krishna\\AppData\\Local\\Temp\\Temp1_heart-disease-uci.zip\\heart.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
x=df.iloc[:,:-1].values

In [5]:
y=df.iloc[:,-1].values

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x1_train=ss.fit_transform(x_train)
x1_test=ss.transform(x_test)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
from sklearn.metrics import *

In [9]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x1_train,y_train)
pred=knn.predict(x1_test)
pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [13]:
for k in range(20):
    k=k+1
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x1_train,y_train)
    pred=knn.predict(x1_test)
    accuracy=accuracy_score(y_test,pred)
    print('accuracy of k=',k,'is',accuracy)

accuracy of k= 1 is 0.7894736842105263
accuracy of k= 2 is 0.7763157894736842
accuracy of k= 3 is 0.8421052631578947
accuracy of k= 4 is 0.8421052631578947
accuracy of k= 5 is 0.8157894736842105
accuracy of k= 6 is 0.8552631578947368
accuracy of k= 7 is 0.868421052631579
accuracy of k= 8 is 0.868421052631579
accuracy of k= 9 is 0.8552631578947368
accuracy of k= 10 is 0.8552631578947368
accuracy of k= 11 is 0.8421052631578947
accuracy of k= 12 is 0.8421052631578947
accuracy of k= 13 is 0.8289473684210527
accuracy of k= 14 is 0.8289473684210527
accuracy of k= 15 is 0.8289473684210527
accuracy of k= 16 is 0.8157894736842105
accuracy of k= 17 is 0.8289473684210527
accuracy of k= 18 is 0.8157894736842105
accuracy of k= 19 is 0.8157894736842105
accuracy of k= 20 is 0.8157894736842105


In [15]:
knn=KNeighborsClassifier(2)
knn.fit(x1_train,y_train)
pred2=knn.predict(x1_test)
pred2

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0], dtype=int64)

In [16]:
confusion=confusion_matrix(y_test,pred2)
confusion

array([[29,  4],
       [13, 30]], dtype=int64)

In [17]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       0.69      0.88      0.77        33
           1       0.88      0.70      0.78        43

    accuracy                           0.78        76
   macro avg       0.79      0.79      0.78        76
weighted avg       0.80      0.78      0.78        76

