In [1]:
import pandas as pd
import keras

Using TensorFlow backend.


In [2]:
from keras.models import Sequential

In [3]:
df=pd.read_csv('C:\\Users\\krishna\\AppData\\Local\\Temp\\Temp1_6410_9356_bundle_archive.zip\\data.csv')
df

URLs  \
0     http://www.bbc.com/news/world-us-canada-414191...   
1     https://www.reuters.com/article/us-filmfestiva...   
2     https://www.nytimes.com/2017/10/09/us/politics...   
3     https://www.reuters.com/article/us-mexico-oil-...   
4     http://www.cnn.com/videos/cnnmoney/2017/10/08/...   
...                                                 ...   
4004  http://beforeitsnews.com/sports/2017/09/trends...   
4005  http://beforeitsnews.com/u-s-politics/2017/10/...   
4006  https://www.activistpost.com/2017/09/ron-paul-...   
4007  https://www.reuters.com/article/us-china-pharm...   
4008  http://beforeitsnews.com/u-s-politics/2017/10/...   

                                               Headline  \
0            Four ways Bob Corker skewered Donald Trump   
1     Linklater's war veteran comedy speaks to moder...   
2     Trump’s Fight With Corker Jeopardizes His Legi...   
3     Egypt's Cheiron wins tie-up with Pemex for Mex...   
4           Jason Aldean opens 'SNL' with Vegas tribute   
...                                                 ...   
4004                                    Trends to Watch   
4005  Trump Jr. Is Soon To Give A 30-Minute Speech F...   
4006        Ron Paul on Trump, Anarchism & the AltRight   
4007  China to accept overseas trial data in bid to ...   
4008  Vice President Mike Pence Leaves NFL Game Beca...   

                                                   Body  Label  
0     Image copyright Getty Images\nOn Sunday mornin...      1  
1     LONDON (Reuters) - “Last Flag Flying”, a comed...      1  
2     The feud broke into public view last week when...      1  
3     MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...      1  
4     Country singer Jason Aldean, who was performin...      1  
...                                                 ...    ...  
4004  Trends to Watch\n% of readers think this story...      0  
4005  Trump Jr. Is Soon To Give A 30-Minute Speech F...      0  
4006                                                NaN      0  
4007  SHANGHAI (Reuters) - China said it plans to ac...      1  
4008  Vice President Mike Pence Leaves NFL Game Beca...      0  

[4009 rows x 4 columns]

In [4]:
df.isnull().any()

URLs        False
Headline    False
Body         True
Label       False
dtype: bool

In [5]:
df=df.dropna()

In [6]:
df.isnull().any()

URLs        False
Headline    False
Body        False
Label       False
dtype: bool

In [7]:
x=df.iloc[:,:-1]

In [8]:
y=df.iloc[:,-1]

In [9]:
import tensorflow as tf

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [11]:
voc_size=5000

In [12]:
message=x.copy()

In [13]:
message.reset_index(inplace=True)

In [14]:
import nltk
import re
from nltk.corpus import stopwords

In [15]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     

[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package ptb to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package qc to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to
[n

[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package word2vec_sample is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\krishna\AppData\Roaming\nltk_data...
[nltk_da

True

In [16]:
sw=stopwords.words('english')

In [17]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()
corpus=[]

In [18]:
for i in range(len(message)):
    review=re.sub('[^a-zA-Z]',' ',message['Headline'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if word not in sw]
    review=' '.join(review)
    corpus.append(review)

In [19]:
onehot=[one_hot(words,voc_size) for words in corpus]
onehot

[[1227, 3843, 904, 1109, 2428, 3533, 3826],
 [4099, 2116, 1416, 2300, 2582, 2847, 545, 3645, 244],
 [3826, 853, 1109, 695, 4601, 1019],
 [661, 3972, 1990, 2638, 3849, 4608, 2074, 651, 3215],
 [2594, 619, 3312, 3072, 2139, 2258],
 [102, 3959, 2001, 4065],
 [3675, 2158, 3606, 2792, 1260, 3826, 1868],
 [4209, 2793, 2408, 3833, 314, 3083, 1603, 859],
 [2123, 2408, 4551, 3560, 3344, 3989, 2792, 4667, 2701],
 [1860, 3264, 1246, 1673, 3833, 4112, 2777, 222, 2937],
 [2544,
  4924,
  3533,
  3826,
  4794,
  4551,
  1184,
  253,
  3361,
  710,
  4646,
  4425,
  3516,
  4945],
 [2977, 700, 1158, 3156, 1213, 4065],
 [1694, 3111, 4752, 3156],
 [3793, 594, 4519, 3515, 3427, 3257],
 [4938, 1561, 366, 4799, 3116, 159, 4751, 4938, 2721, 3167],
 [4035, 1922, 4438, 2085, 2792, 747],
 [2545, 4701, 4035, 1922, 3645, 1595, 2792],
 [3826, 873, 3557, 4056, 1704, 853],
 [3826, 155, 9, 1738, 2058, 1094, 2710, 4480, 977],
 [3618, 1200, 3826, 1860, 1532, 1661],
 [4412, 1755, 3126, 437, 2158, 75, 2847, 1569],
 [42

In [20]:
sent_length=20

In [21]:
embedded_docs=pad_sequences(onehot,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2428 3533 3826]
 [   0    0    0 ...  545 3645  244]
 [   0    0    0 ...  695 4601 1019]
 ...
 [   0    0    0 ... 4529 3038  873]
 [   0    0    0 ... 4255  241 2139]
 [   0    0    0 ... 4014 4800 4846]]


In [22]:
from tensorflow.keras.layers import Dropout

In [23]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=[['accuracy']])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
dropout (Dropout)            (None, 20, 40)            0         
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [24]:
import numpy as np

In [25]:
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [26]:
x_final.shape

(3988, 20)

In [27]:
y_final.shape

(3988,)

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.33,random_state=43)

In [29]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),batch_size=64,epochs=10)

Train on 2671 samples, validate on 1317 samples
Epoch 1/10
2671/2671 [==============================] - 16s 6ms/sample - loss: 0.6857 - accuracy: 0.5459 - val_loss: 0.6658 - val_accuracy: 0.7206
Epoch 2/10
2671/2671 [==============================] - 4s 2ms/sample - loss: 0.4984 - accuracy: 0.7986 - val_loss: 0.4673 - val_accuracy: 0.7684
Epoch 3/10
2671/2671 [==============================] - 4s 2ms/sample - loss: 0.2888 - accuracy: 0.8892 - val_loss: 0.5262 - val_accuracy: 0.7661
Epoch 4/10
2671/2671 [==============================] - 4s 2ms/sample - loss: 0.1770 - accuracy: 0.9386 - val_loss: 0.5104 - val_accuracy: 0.8011
Epoch 5/10
2671/2671 [==============================] - 4s 2ms/sample - loss: 0.1098 - accuracy: 0.9671 - val_loss: 0.6404 - val_accuracy: 0.8071
Epoch 6/10
2671/2671 [==============================] - 7s 3ms/sample - loss: 0.0735 - accuracy: 0.9757 - val_loss: 0.7188 - val_accuracy: 0.8094
Epoch 7/10
2671/2671 [==============================] - 6s 2ms/sample - los

In [30]:
from sklearn.metrics import *

In [31]:
pred=model.predict_classes(x_test)

In [32]:
cf=confusion_matrix(y_test,pred)
cf

array([[586, 124],
       [145, 462]], dtype=int64)

In [33]:
accuracy=accuracy_score(y_test,pred)
accuracy*100

79.57479119210326