In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.DataFrame({'city':['hyd','bng','che','bng','hyd','che','hyd','bng','che'],'sqft':[3000,3300,4000,4200,4300,4500,4700,4800,5000],'bedroom':[3,2,3,4,2,3,4,3,2],'price':[2200000,2400000,2800000,3000000,3200000,3500000,4000000,4200000,4500000]})
df

city  sqft  bedroom    price
0  hyd  3000        3  2200000
1  bng  3300        2  2400000
2  che  4000        3  2800000
3  bng  4200        4  3000000
4  hyd  4300        2  3200000
5  che  4500        3  3500000
6  hyd  4700        4  4000000
7  bng  4800        3  4200000
8  che  5000        2  4500000

In [3]:
x=df.iloc[:,:-1].values
x

array([['hyd', 3000, 3],
       ['bng', 3300, 2],
       ['che', 4000, 3],
       ['bng', 4200, 4],
       ['hyd', 4300, 2],
       ['che', 4500, 3],
       ['hyd', 4700, 4],
       ['bng', 4800, 3],
       ['che', 5000, 2]], dtype=object)

In [4]:
y=df.iloc[:,-1].values
y1=y.reshape(-1,1)

In [5]:
x1=df.iloc[:,0].values
x1.reshape(-1,1)

array([['hyd'],
       ['bng'],
       ['che'],
       ['bng'],
       ['hyd'],
       ['che'],
       ['hyd'],
       ['bng'],
       ['che']], dtype=object)

In [6]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder(categories='auto',sparse=False)
Y=onehotencoder.fit_transform(x[:,0].reshape(-1,1))
Y

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [7]:
array=np.hstack([Y,x[:,[1,2]]])
array

array([[0.0, 0.0, 1.0, 3000, 3],
       [1.0, 0.0, 0.0, 3300, 2],
       [0.0, 1.0, 0.0, 4000, 3],
       [1.0, 0.0, 0.0, 4200, 4],
       [0.0, 0.0, 1.0, 4300, 2],
       [0.0, 1.0, 0.0, 4500, 3],
       [0.0, 0.0, 1.0, 4700, 4],
       [1.0, 0.0, 0.0, 4800, 3],
       [0.0, 1.0, 0.0, 5000, 2]], dtype=object)

In [8]:
final_array=np.hstack([array,y1])
final_array

array([[0.0, 0.0, 1.0, 3000, 3, 2200000],
       [1.0, 0.0, 0.0, 3300, 2, 2400000],
       [0.0, 1.0, 0.0, 4000, 3, 2800000],
       [1.0, 0.0, 0.0, 4200, 4, 3000000],
       [0.0, 0.0, 1.0, 4300, 2, 3200000],
       [0.0, 1.0, 0.0, 4500, 3, 3500000],
       [0.0, 0.0, 1.0, 4700, 4, 4000000],
       [1.0, 0.0, 0.0, 4800, 3, 4200000],
       [0.0, 1.0, 0.0, 5000, 2, 4500000]], dtype=object)

In [9]:
df2=pd.DataFrame(data=final_array,columns=['hyd','bng','che','sqft','bedrooms','price'])
df2

hyd bng che  sqft bedrooms    price
0   0   0   1  3000        3  2200000
1   1   0   0  3300        2  2400000
2   0   1   0  4000        3  2800000
3   1   0   0  4200        4  3000000
4   0   0   1  4300        2  3200000
5   0   1   0  4500        3  3500000
6   0   0   1  4700        4  4000000
7   1   0   0  4800        3  4200000
8   0   1   0  5000        2  4500000

In [10]:
A=df2.iloc[:,:-1].values
A

array([[0.0, 0.0, 1.0, 3000, 3],
       [1.0, 0.0, 0.0, 3300, 2],
       [0.0, 1.0, 0.0, 4000, 3],
       [1.0, 0.0, 0.0, 4200, 4],
       [0.0, 0.0, 1.0, 4300, 2],
       [0.0, 1.0, 0.0, 4500, 3],
       [0.0, 0.0, 1.0, 4700, 4],
       [1.0, 0.0, 0.0, 4800, 3],
       [0.0, 1.0, 0.0, 5000, 2]], dtype=object)

In [23]:
B=df2.iloc[:,-1].values
C=B.reshape(-1,1)
C

array([[2200000],
       [2400000],
       [2800000],
       [3000000],
       [3200000],
       [3500000],
       [4000000],
       [4200000],
       [4500000]], dtype=object)

In [29]:
from sklearn.model_selection import train_test_split
A_train,A_test,C_train,C_test=train_test_split(A,B,test_size=0.25,random_state=0)
print(A_train,A_test,C_train,C_test)

[[0.0 0.0 1.0 4300 2]
 [0.0 1.0 0.0 5000 2]
 [0.0 0.0 1.0 4700 4]
 [1.0 0.0 0.0 4200 4]
 [0.0 0.0 1.0 3000 3]
 [0.0 1.0 0.0 4500 3]] [[1.0 0.0 0.0 4800 3]
 [0.0 1.0 0.0 4000 3]
 [1.0 0.0 0.0 3300 2]] [3200000 4500000 4000000 3000000 2200000 3500000] [4200000 2800000 2400000]


In [13]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(A_train,C_train)
C_pred=lr.predict(A_test)
C_pred


array([3577358.49056606, 3235849.05660376, 1935849.0566038 ])

In [14]:
new=lr.predict([[1,0,0,4000,4]])
new
np.round(new,2)

array([2788679.25])

In [15]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
from numpy import sqrt
rmse=sqrt(mean_squared_error(C_test,C_pred))
rmse

514160.46382043854

In [16]:
mae=mean_absolute_error(C_test,C_pred)
mae

507547.1698113002

In [17]:
from sklearn.metrics import r2_score
r2score=r2_score(C_test,C_pred)
Accuracy=r2score*100
Accuracy

55.6110290484247

In [18]:
df=pd.DataFrame({'actual':C_test,'predicted':np.round(C_pred,2)})
df

actual   predicted
0  4200000  3577358.49
1  2800000  3235849.06
2  2400000  1935849.06