In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('C:\\Users\\krishna\\divesh\\50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [6]:
df1=df._get_numeric_data()
df1.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [7]:
x=df1.iloc[:,:-1].values
x

array([[165349.2 , 136897.8 , 471784.1 ],
       [162597.7 , 151377.59, 443898.53],
       [153441.51, 101145.55, 407934.54],
       [144372.41, 118671.85, 383199.62],
       [142107.34,  91391.77, 366168.42],
       [131876.9 ,  99814.71, 362861.36],
       [134615.46, 147198.87, 127716.82],
       [130298.13, 145530.06, 323876.68],
       [120542.52, 148718.95, 311613.29],
       [123334.88, 108679.17, 304981.62],
       [101913.08, 110594.11, 229160.95],
       [100671.96,  91790.61, 249744.55],
       [ 93863.75, 127320.38, 249839.44],
       [ 91992.39, 135495.07, 252664.93],
       [119943.24, 156547.42, 256512.92],
       [114523.61, 122616.84, 261776.23],
       [ 78013.11, 121597.55, 264346.06],
       [ 94657.16, 145077.58, 282574.31],
       [ 91749.16, 114175.79, 294919.57],
       [ 86419.7 , 153514.11,      0.  ],
       [ 76253.86, 113867.3 , 298664.47],
       [ 78389.47, 153773.43, 299737.29],
       [ 73994.56, 122782.75, 303319.26],
       [ 67532.53, 105751.03, 3047

In [9]:
y=df1.iloc[:,-1].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
print(x_train,x_test,y_train,y_test)

[[ 46426.07 157693.92 210797.67]
 [ 91749.16 114175.79 294919.57]
 [130298.13 145530.06 323876.68]
 [119943.24 156547.42 256512.92]
 [  1000.23 124153.04   1903.93]
 [   542.05  51743.15      0.  ]
 [ 65605.48 153032.06 107138.38]
 [114523.61 122616.84 261776.23]
 [ 61994.48 115641.28  91131.24]
 [ 63408.86 129219.61  46085.25]
 [ 78013.11 121597.55 264346.06]
 [ 23640.93  96189.63 148001.11]
 [ 76253.86 113867.3  298664.47]
 [ 15505.73 127382.3   35534.17]
 [120542.52 148718.95 311613.29]
 [ 91992.39 135495.07 252664.93]
 [ 64664.71 139553.16 137962.62]
 [131876.9   99814.71 362861.36]
 [ 94657.16 145077.58 282574.31]
 [ 28754.33 118546.05 172795.67]
 [     0.   116983.8   45173.06]
 [162597.7  151377.59 443898.53]
 [ 93863.75 127320.38 249839.44]
 [ 44069.95  51283.14 197029.42]
 [ 77044.01  99281.34 140574.81]
 [134615.46 147198.87 127716.82]
 [ 67532.53 105751.03 304768.73]
 [ 28663.76 127056.21 201126.82]
 [ 78389.47 153773.43 299737.29]
 [ 86419.7  153514.11      0.  ]
 [123334.8

In [11]:
ols=sm.OLS(endog=y_train,exog=x_train).fit()
print(ols.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.989
Model:                            OLS   Adj. R-squared (uncentered):              0.988
Method:                 Least Squares   F-statistic:                              1058.
Date:                Tue, 31 Mar 2020   Prob (F-statistic):                    1.27e-33
Time:                        17:27:26   Log-Likelihood:                         -400.47
No. Observations:                  37   AIC:                                      806.9
Df Residuals:                      34   BIC:                                      811.8
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [12]:
y_pred=ols.predict(x_test)
y_pred

array([119071.61186646, 120205.20706258, 126407.27636531,  60227.31172473,
       171297.92853468, 119038.5356409 ,  49458.10090373, 103110.98123458,
       115433.09338057, 157102.39829009,  89620.09185851,  75917.03890371,
       113158.99317758])

In [13]:
DataFrame=pd.DataFrame({'actual':y_test,'predict':y_pred})
DataFrame

actual        predict
0   103282.38  119071.611866
1   144259.40  120205.207063
2   146121.95  126407.276365
3    77798.83   60227.311725
4   191050.39  171297.928535
5   105008.31  119038.535641
6    81229.06   49458.100904
7    97483.56  103110.981235
8   110352.25  115433.093381
9   166187.94  157102.398290
10   96778.92   89620.091859
11   96479.51   75917.038904
12  105733.54  113158.993178

In [14]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
from numpy import sqrt
rmse=sqrt(mean_squared_error(y_pred,y_test))
rmse

17076.665949597347

In [15]:
mae=mean_absolute_error(y_pred,y_test)
mae

15201.832435134329

In [18]:
from sklearn.metrics import r2_score
R2_score=r2_score(y_pred,y_test)
Accuracy=R2_score*100
Accuracy

73.51269390839416