In [1]:
import numpy as np
import pandas as pd

In [7]:
from numpy import mean
from numpy import array
from numpy import cov
from numpy.linalg import eig

In [11]:
a=array([[3,5],[4,6],[9,8]])
a

array([[3, 5],
       [4, 6],
       [9, 8]])

In [12]:
mean=mean(a.T,axis=1)
mean

array([5.33333333, 6.33333333])

In [13]:
c=a-mean
c

array([[-2.33333333, -1.33333333],
       [-1.33333333, -0.33333333],
       [ 3.66666667,  1.66666667]])

In [23]:
co=cov(c.T)
co

array([[10.33333333,  4.83333333],
       [ 4.83333333,  2.33333333]])

In [25]:
values,vectors=eig(co)
print(values)
print(vectors)

[12.60717674  0.05948993]
[[ 0.90486676 -0.42569489]
 [ 0.42569489  0.90486676]]


In [26]:
pca=vectors.T.dot(c.T)
print(pca.T)

[[-2.67894897 -0.21320093]
 [-1.34838731  0.26597094]
 [ 4.02733628 -0.05277001]]
