In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import *

In [4]:
boston=load_boston()

In [5]:
x=boston['data']

In [6]:
y=boston['target']

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [9]:
df1=pd.DataFrame(boston['data'])
df1.columns=boston['feature_names']
df1['price']=boston['target']

In [10]:
df1

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [11]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x1_train=ss.fit_transform(x_train)
x1_test=ss.transform(x_test)

In [16]:
from sklearn.linear_model import Ridge

In [18]:

ridge1=Ridge(alpha=0.5,normalize=True)
ridge1.fit(x1_train,y_train)
pred=ridge1.predict(x1_test)
pred

array([26.37929882, 20.28619467, 27.65938171, 12.56120107, 22.31196601,
       20.9320166 , 18.96525898, 22.23761747, 18.92438473, 20.17377552,
        7.77316482, 15.25365758, 17.11992863,  7.48094749, 35.82947795,
       32.12813417, 20.33150925, 35.26989917, 28.99062649, 23.12138943,
       24.82636385, 22.98801371, 20.72910288, 28.0908385 , 22.88362062,
        8.65444395, 19.48614655, 19.70655971, 33.46364634, 21.28074507,
       17.16628639, 17.71813784, 22.27311628, 24.32367   , 27.02908994,
       19.13341546, 12.53768342, 21.65357666, 16.09315599, 14.98681773,
       25.63615527, 21.99423412, 24.65929173, 14.49335501, 26.4512843 ,
       25.2936696 , 21.34308649, 24.29067252, 13.68152215, 24.13023959,
       22.65687426, 19.23332136, 23.49792389, 32.0194618 , 15.22082672,
       23.15803885, 22.94299126, 20.32130495, 12.59477147, 22.7620238 ,
       22.98386214, 22.48867458, 30.92322624, 28.67561582, 16.78556041,
       30.59493067, 18.55101547, 22.33985947, 17.46199614, 22.90

In [19]:
ridge1.intercept_

22.608707124010593

In [20]:
ridge1.coef_

array([-0.63938955,  0.48298157, -0.57461857,  0.60543411, -0.51521289,
        2.41105555, -0.31549737, -0.91601735,  0.0470677 , -0.56488623,
       -1.59628916,  0.66233648, -2.29266982])

In [21]:
from sklearn.metrics import *

In [22]:
accuracy=r2_score(y_test,pred)
accuracy*100

55.63817212362703

In [23]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=0.1,normalize=True)
lasso.fit(x1_train,y_train)
pred1=lasso.predict(x1_test)
pred1

array([25.94083694, 22.82442919, 24.84959463, 15.52689178, 22.35831464,
       21.78182878, 21.02424459, 22.21475577, 18.71474288, 22.48919046,
       16.89958525, 18.6565382 , 19.33650377,  9.53068615, 33.91226296,
       30.32990625, 22.33585777, 32.52328815, 27.65737213, 22.64565028,
       24.84097733, 23.605698  , 20.06692317, 26.07208693, 22.17664459,
       14.20616417, 19.66362742, 21.35487015, 31.86651843, 20.2146278 ,
       18.77069176, 20.02086635, 23.14934957, 23.04840257, 25.54915353,
       19.23997063, 14.11913652, 22.13534383, 19.42681591, 15.8733372 ,
       25.24182393, 20.64202776, 24.57489645, 16.51390889, 26.46403042,
       24.87896692, 20.875954  , 22.88932963, 12.71468551, 23.99030874,
       23.00288071, 18.00450126, 22.64102702, 32.14683648, 17.32935657,
       21.65002818, 21.74304622, 21.17944843, 21.21846152, 19.32122131,
       23.68012865, 21.98973986, 29.41100274, 27.98151564, 18.92214921,
       28.78997396, 20.27810157, 20.85966546, 19.89538379, 22.10

In [24]:
lasso.intercept_

22.608707124010586

In [25]:
lasso.coef_

array([-0.        ,  0.        , -0.        ,  0.        , -0.        ,
        2.01484042, -0.        ,  0.        , -0.        , -0.        ,
       -1.16405045,  0.        , -3.35420208])

In [26]:
accuracy=r2_score(y_test,pred1)
accuracy*100

54.555660013376794

In [27]:
from sklearn.linear_model import ElasticNet

In [29]:
elasticnet=ElasticNet(random_state=0)
elasticnet.fit(x1_train,y_train)
pred2=elasticnet.predict(x1_test)

In [30]:
pred2

array([26.07932198, 20.38072697, 26.56744167, 13.49674854, 22.59722444,
       21.25055451, 19.19067624, 22.46018331, 18.41959543, 20.63876422,
       10.72516751, 16.22373597, 17.85730193,  8.50846508, 34.27534834,
       31.44459254, 20.63019103, 34.27593165, 27.9296729 , 22.7556009 ,
       24.79039067, 23.21040168, 20.29711218, 26.82336807, 22.81072164,
        9.93798179, 19.96208812, 20.45765896, 32.64737722, 21.12847848,
       17.6464996 , 18.41802242, 23.64894472, 24.50429569, 26.34977264,
       18.57136948, 13.38239639, 20.60414821, 16.90453818, 15.51050753,
       25.58130891, 21.90876816, 24.86730196, 15.13778111, 27.09041213,
       25.59183656, 22.16918599, 23.67658812, 14.201887  , 23.79397843,
       22.44835658, 18.64883204, 23.28781313, 32.5631697 , 16.04581886,
       23.21942019, 22.93680922, 21.7903142 , 14.65169829, 21.85809917,
       24.16963873, 22.51572506, 30.00951484, 27.68548764, 17.13147769,
       29.28043566, 19.21146399, 23.33959542, 18.06245981, 22.40