In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv('C:\\Users\\krishna\\AppData\\Local\\Temp\\Temp1_housedata.zip\\data.csv')
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [14]:
df1=df._get_numeric_data()
df1

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     3.130000e+05       3.0       1.50         1340      7912     1.5   
1     2.384000e+06       5.0       2.50         3650      9050     2.0   
2     3.420000e+05       3.0       2.00         1930     11947     1.0   
3     4.200000e+05       3.0       2.25         2000      8030     1.0   
4     5.500000e+05       4.0       2.50         1940     10500     1.0   
...            ...       ...        ...          ...       ...     ...   
4595  3.081667e+05       3.0       1.75         1510      6360     1.0   
4596  5.343333e+05       3.0       2.50         1460      7573     2.0   
4597  4.169042e+05       3.0       2.50         3010      7014     2.0   
4598  2.034000e+05       4.0       2.00         2090      6630     1.0   
4599  2.206000e+05       3.0       2.50         1490      8102     2.0   

      waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0              0     0          3        1340              0      1955   
1              0     4          5        3370            280      1921   
2              0     0          4        1930              0      1966   
3              0     0          4        1000           1000      1963   
4              0     0          4        1140            800      1976   
...          ...   ...        ...         ...            ...       ...   
4595           0     0          4        1510              0      1954   
4596           0     0          3        1460              0      1983   
4597           0     0          3        3010              0      2009   
4598           0     0          3        1070           1020      1974   
4599           0     0          4        1490              0      1990   

      yr_renovated  
0             2005  
1                0  
2                0  
3                0  
4             1992  
...            ...  
4595          1979  
4596          2009  
4597             0  
4598             0  
4599             0  

[4600 rows x 13 columns]

In [4]:
df1.isnull().any()

price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront       False
view             False
condition        False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated     False
dtype: bool

In [5]:
y=df1.iloc[:,0].values
y

array([ 313000.      , 2384000.      ,  342000.      , ...,
        416904.166667,  203400.      ,  220600.      ])

In [6]:
x=df1.iloc[:,1:].values
x

array([[3.000e+00, 1.500e+00, 1.340e+03, ..., 0.000e+00, 1.955e+03,
        2.005e+03],
       [5.000e+00, 2.500e+00, 3.650e+03, ..., 2.800e+02, 1.921e+03,
        0.000e+00],
       [3.000e+00, 2.000e+00, 1.930e+03, ..., 0.000e+00, 1.966e+03,
        0.000e+00],
       ...,
       [3.000e+00, 2.500e+00, 3.010e+03, ..., 0.000e+00, 2.009e+03,
        0.000e+00],
       [4.000e+00, 2.000e+00, 2.090e+03, ..., 1.020e+03, 1.974e+03,
        0.000e+00],
       [3.000e+00, 2.500e+00, 1.490e+03, ..., 0.000e+00, 1.990e+03,
        0.000e+00]])

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [8]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=0.1,normalize=True)
lasso.fit(x_train,y_train)
y_pred=lasso.predict(x_test)
y_pred

C:\Users\krishna\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 6756005002076.125, tolerance: 129786195730.44897
  positive)


array([507972.41986064, 632510.83107803, 247662.44789488, ...,
       256900.62932974, 655655.39077625, 629558.64824456])

In [10]:
lasso.coef_

array([-5.88039480e+04,  6.49130450e+04,  2.46636258e+02, -6.81996336e-01,
        3.18432294e+04,  3.11901764e+05,  4.43919916e+04,  3.50258018e+04,
        1.05487658e+00, -1.63977254e+01, -2.29191913e+03,  7.70514201e+00])

In [9]:
df2=pd.DataFrame({'Actual':y_test,'predicted':y_pred})
df2

Actual      predicted
0      289000.0  507972.419861
1      429900.0  632510.831078
2      129000.0  247662.447895
3      600000.0  577855.706013
4     1298000.0  776858.094774
...         ...            ...
1145   513000.0  439956.700154
1146   445000.0  348607.049751
1147   214750.0  256900.629330
1148   547000.0  655655.390776
1149   527000.0  629558.648245

[1150 rows x 2 columns]

In [17]:
new_pred=lasso.predict([[7.0,3,2700,5600,3,0,3,6,5000,1000,1990,2010]])
new_pred

array([754806.41097675])

In [19]:
from sklearn.linear_model import Ridge
ridge=Ridge(alpha=0.5,normalize=True)
ridge.fit(x_train,y_train)
y_pred=ridge.predict(x_test)
y_pred

array([516890.45785835, 628300.20687344, 244969.62307642, ...,
       317544.55099776, 660956.30204292, 713535.34816806])

In [20]:
ridge.coef_

array([-6.73031855e+03,  5.62573189e+04,  8.28336295e+01, -2.33189456e-01,
        2.98863454e+04,  2.80729151e+05,  4.73545900e+04,  2.82341124e+04,
        8.08861455e+01,  8.37899245e+01, -1.11142708e+03,  6.16902686e+00])

In [24]:
from sklearn.linear_model import ElasticNet
elasticnet=ElasticNet(random_state=0)
elasticnet.fit(x_train,y_train)
y_pred=elasticnet.predict(x_test)
y_pred

C:\Users\krishna\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 540832492238942.6, tolerance: 129786195730.44897
  positive)


array([495568.99565887, 643451.98286598, 208877.28666606, ...,
       270961.31254148, 661285.84078415, 680162.45192325])

In [25]:
elasticnet.coef_

array([-2.85013499e+04,  1.84291328e+04,  2.67771971e+02, -7.16449091e-01,
        1.16288973e+04,  4.86228584e+03,  3.08284564e+04,  1.21481370e+04,
        2.83576075e-02, -1.80922819e+01, -2.19150679e+03, -4.83191490e-01])