In [2]:
import matplotlib.pyplot as plt
import numpy as np
import sklearn.datasets
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import seaborn as sns

In [3]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston['data']
y = boston['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [4]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [6]:
import pandas as pd
bos=pd.DataFrame(boston['data'])
bos.columns=boston['feature_names']
bos['price']=boston['target']
bos.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

# Lasso Regression

In [7]:
from sklearn.linear_model import Lasso

lassoReg = Lasso(alpha=0.1, normalize=True)

lassoReg.fit(X_train,y_train)

Lasso_pred = lassoReg.predict(X_train)

In [8]:
Lasso_pred

array([17.46753461, 22.39397937, 28.88771718, 20.0271742 , 16.88925514,
       18.21747249, 22.47203293, 18.43367023, 29.2540283 , 23.30558688,
       15.32125211, 26.25489382, 14.35657438, 16.69881629, 20.61922127,
       28.4172679 , 27.47249965, 25.07022995, 18.7643928 , 29.56877808,
       28.28936876, 17.16658609, 10.16946123, 27.32754685, 26.25912891,
        7.20835045, 25.45147017, 19.17432   , 28.19756381, 18.75049675,
       17.89842886, 20.04590386, 15.16164059, 14.74843899, 21.7094738 ,
       30.13427358, 29.7890015 , 26.94909804, 21.23636859, 23.48762525,
       25.71225993, 24.16533937, 18.68700765, 28.80086776, 12.99918347,
       20.90251843, 27.72718722, 20.04401298, 17.13263694, 18.87637675,
       15.53911084, 24.05416059, 24.38515138, 19.94754511, 20.45686383,
       21.68889128, 23.71190445, 17.08923925, 25.84407875, 24.69294628,
       27.3958693 , 31.16846859, 20.34500645, 16.79344943, 29.08360927,
       28.39756286, 21.3761634 , 33.27204137, 25.42150096, 26.10

In [9]:
lassoReg.coef_

array([-0.        ,  0.        , -0.        ,  0.        , -0.        ,
        2.90961743, -0.        ,  0.        , -0.        , -0.        ,
       -0.53175402,  0.        , -0.46629874])

# Ridge Regression

In [8]:
from sklearn.linear_model import Ridge

## training the model

ridgeReg = Ridge(alpha=0.5, normalize=True)

ridgeReg.fit(X_train,y_train)

Ridge_pred = ridgeReg.predict(X_test)
Ridge_pred

array([26.37929882, 20.28619467, 27.65938171, 12.56120107, 22.31196601,
       20.9320166 , 18.96525898, 22.23761747, 18.92438473, 20.17377552,
        7.77316482, 15.25365758, 17.11992863,  7.48094749, 35.82947795,
       32.12813417, 20.33150925, 35.26989917, 28.99062649, 23.12138943,
       24.82636385, 22.98801371, 20.72910288, 28.0908385 , 22.88362062,
        8.65444395, 19.48614655, 19.70655971, 33.46364634, 21.28074507,
       17.16628639, 17.71813784, 22.27311628, 24.32367   , 27.02908994,
       19.13341546, 12.53768342, 21.65357666, 16.09315599, 14.98681773,
       25.63615527, 21.99423412, 24.65929173, 14.49335501, 26.4512843 ,
       25.2936696 , 21.34308649, 24.29067252, 13.68152215, 24.13023959,
       22.65687426, 19.23332136, 23.49792389, 32.0194618 , 15.22082672,
       23.15803885, 22.94299126, 20.32130495, 12.59477147, 22.7620238 ,
       22.98386214, 22.48867458, 30.92322624, 28.67561582, 16.78556041,
       30.59493067, 18.55101547, 22.33985947, 17.46199614, 22.90

In [9]:
ridgeReg.coef_

array([-7.75269225e-02,  2.03115304e-02, -8.19452309e-02,  2.43912727e+00,
       -4.44051827e+00,  3.48178901e+00, -1.11968153e-02, -4.37832281e-01,
        5.43215991e-03, -3.30162464e-03, -7.29206525e-01,  7.43766276e-03,
       -3.18725296e-01])

# ElasticNet Regression

In [10]:
from sklearn.linear_model import ElasticNet

## training the model

Elreg = ElasticNet(random_state=0)
        

Elreg.fit(X_train,y_train)

Elastic_pred = Elreg.predict(X_test)

Elastic_pred

array([24.29141771, 24.0149099 , 27.1536099 , 14.33843898, 20.20800491,
       22.5454802 , 20.67344058, 24.07528455, 21.72694511, 20.06223969,
        7.59197747, 12.78085764, 17.21619803,  7.8120711 , 34.9455129 ,
       31.28262666, 21.39438611, 34.96389209, 30.34225008, 24.82202327,
       25.61966326, 25.28390492, 20.12472705, 29.768894  , 23.83411544,
       16.86177734, 19.51874771, 22.40710632, 31.28338363, 19.74295427,
       16.97703945, 19.11155086, 22.08103343, 24.37133543, 28.58994365,
       19.50364699,  9.92153172, 24.03416699, 15.31369518, 12.2528776 ,
       25.62214828, 21.04983362, 22.46350634, 15.98384821, 23.6068559 ,
       25.65532997, 19.87900746, 23.62037987, 13.04485555, 23.5011522 ,
       21.6621808 , 17.42623099, 24.92673137, 27.22648269, 14.79757773,
       21.8740834 , 22.10692667, 17.48899249, 17.0316856 , 19.52309798,
       21.64764071, 22.22800966, 31.06460593, 30.84107776, 17.82511425,
       31.66772885, 17.66873194, 18.82360277, 15.0831792 , 23.22

In [11]:
Elreg.coef_

array([-0.0783184 ,  0.05270179, -0.03090927,  0.        , -0.        ,
        0.86864688,  0.01250035, -0.80499125,  0.22550957, -0.01468991,
       -0.80977541,  0.00738361, -0.7276762 ])