In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('C:\\Users\\krishna\\AppData\\Local\\Temp\\Temp1_seattle-house-sales-prices.zip\\house_sales.csv')
df

id             date   price  bedrooms  bathrooms  sqft_living  \
0      7129300520  20141013T000000  221900         3       1.00         1180   
1      6414100192  20141209T000000  538000         3       2.25         2570   
2      5631500400  20150225T000000  180000         2       1.00          770   
3      2487200875  20141209T000000  604000         4       3.00         1960   
4      1954400510  20150218T000000  510000         3       2.00         1680   
...           ...              ...     ...       ...        ...          ...   
21608   263000018  20140521T000000  360000         3       2.50         1530   
21609  6600060120  20150223T000000  400000         4       2.50         2310   
21610  1523300141  20140623T000000  402101         2       0.75         1020   
21611   291310100  20150116T000000  400000         3       2.50         1600   
21612  1523300157  20141015T000000  325000         2       0.75         1020   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
0          5650     1.0           0     0  ...      7        1180   
1          7242     2.0           0     0  ...      7        2170   
2         10000     1.0           0     0  ...      6         770   
3          5000     1.0           0     0  ...      7        1050   
4          8080     1.0           0     0  ...      8        1680   
...         ...     ...         ...   ...  ...    ...         ...   
21608      1131     3.0           0     0  ...      8        1530   
21609      5813     2.0           0     0  ...      8        2310   
21610      1350     2.0           0     0  ...      7        1020   
21611      2388     2.0           0     0  ...      8        1600   
21612      1076     2.0           0     0  ...      7        1020   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0                  0      1955             0    98178  47.5112 -122.257   
1                400      1951          1991    98125  47.7210 -122.319   
2                  0      1933             0    98028  47.7379 -122.233   
3                910      1965             0    98136  47.5208 -122.393   
4                  0      1987             0    98074  47.6168 -122.045   
...              ...       ...           ...      ...      ...      ...   
21608              0      2009             0    98103  47.6993 -122.346   
21609              0      2014             0    98146  47.5107 -122.362   
21610              0      2009             0    98144  47.5944 -122.299   
21611              0      2004             0    98027  47.5345 -122.069   
21612              0      2008             0    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15  
0               1340        5650  
1               1690        7639  
2               2720        8062  
3               1360        5000  
4               1800        7503  
...              ...         ...  
21608           1530        1509  
21609           1830        7200  
21610           1020        2007  
21611           1410        1287  
21612           1020        1357  

[21613 rows x 21 columns]

In [6]:
df1=pd.DataFrame(data=df,columns=('sqft_living','bedrooms','sqft_lot','floors','grade','sqft_above','sqft_basement','lat','sqft_living15','sqft_lot15','price'))
df1                                  

sqft_living  bedrooms  sqft_lot  floors  grade  sqft_above  \
0             1180         3      5650     1.0      7        1180   
1             2570         3      7242     2.0      7        2170   
2              770         2     10000     1.0      6         770   
3             1960         4      5000     1.0      7        1050   
4             1680         3      8080     1.0      8        1680   
...            ...       ...       ...     ...    ...         ...   
21608         1530         3      1131     3.0      8        1530   
21609         2310         4      5813     2.0      8        2310   
21610         1020         2      1350     2.0      7        1020   
21611         1600         3      2388     2.0      8        1600   
21612         1020         2      1076     2.0      7        1020   

       sqft_basement      lat  sqft_living15  sqft_lot15   price  
0                  0  47.5112           1340        5650  221900  
1                400  47.7210           1690        7639  538000  
2                  0  47.7379           2720        8062  180000  
3                910  47.5208           1360        5000  604000  
4                  0  47.6168           1800        7503  510000  
...              ...      ...            ...         ...     ...  
21608              0  47.6993           1530        1509  360000  
21609              0  47.5107           1830        7200  400000  
21610              0  47.5944           1020        2007  402101  
21611              0  47.5345           1410        1287  400000  
21612              0  47.5941           1020        1357  325000  

[21613 rows x 11 columns]

In [7]:
x=df1.iloc[:,:-1].values

In [8]:
y=df1.iloc[:,-1].values

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [16]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=0.2,normalize=False)
lasso.fit(x_train,y_train)
pred=lasso.predict(x_test)
pred

C:\Users\krishna\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 391139870686338.25, tolerance: 219486686244.4991
  positive)


array([ 447810.34341453, 1470534.59390705,  481999.97142929, ...,
        800672.81342616,  365660.23938143,  467791.27677837])

In [17]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
from numpy import sqrt
rmse=sqrt(mean_squared_error(y_test,pred))
rmse

228843.45874472344

In [18]:
from sklearn.metrics import r2_score
r2score=r2_score(y_test,pred)
accuracy=r2score*100
accuracy

60.57731229233565

In [12]:
lasso.coef_

array([ 2.64111310e+02, -3.89068651e+04,  2.08760419e-01, -2.82715478e+04,
        8.20734402e+04, -6.04100084e+01, -2.07479789e+01,  6.41999866e+05,
        2.50287574e+01, -5.74936860e-01])

In [20]:
from sklearn.linear_model import Ridge
ridge=Ridge(alpha=0.5,normalize=False)
ridge.fit(x_train,y_train)
ridgepred=ridge.predict(x_test)
ridgepred

array([ 447670.1257214 , 1470463.90630929,  481880.61468016, ...,
        800827.61772978,  365585.14511169,  467639.32540717])

In [26]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
from numpy import sqrt
rmse=sqrt(mean_squared_error(y_test,ridgepred))
rmse

228843.10536579072

In [21]:
from sklearn.metrics import r2_score
r2score=r2_score(y_test,ridgepred)
accuracy=r2score*100
accuracy

60.57743404487888

In [24]:
from sklearn.linear_model import ElasticNet
EN=ElasticNet(random_state=0)
EN.fit(x_train,y_train)
ENpred=EN.predict(x_test)
ENpred

C:\Users\krishna\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:475: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 511452141605213.2, tolerance: 219486686244.4991
  positive)


array([ 373828.6492398 , 1359452.92017829,  387330.45411267, ...,
        862467.72793713,  301901.43635659,  383989.25637463])

In [27]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
from numpy import sqrt
rmse=sqrt(mean_squared_error(y_test,ENpred))
rmse

247651.8679352631

In [25]:
from sklearn.metrics import r2_score
r2score=r2_score(y_test,ENpred)
accuracy=r2score*100
accuracy

53.83079040389629