In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('C:\\Users\\krishna\\AppData\\Local\\Temp\\Temp1_seattle-house-sales-prices.zip\\house_sales.csv')
df

id             date   price  bedrooms  bathrooms  sqft_living  \
0      7129300520  20141013T000000  221900         3       1.00         1180   
1      6414100192  20141209T000000  538000         3       2.25         2570   
2      5631500400  20150225T000000  180000         2       1.00          770   
3      2487200875  20141209T000000  604000         4       3.00         1960   
4      1954400510  20150218T000000  510000         3       2.00         1680   
...           ...              ...     ...       ...        ...          ...   
21608   263000018  20140521T000000  360000         3       2.50         1530   
21609  6600060120  20150223T000000  400000         4       2.50         2310   
21610  1523300141  20140623T000000  402101         2       0.75         1020   
21611   291310100  20150116T000000  400000         3       2.50         1600   
21612  1523300157  20141015T000000  325000         2       0.75         1020   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
0          5650     1.0           0     0  ...      7        1180   
1          7242     2.0           0     0  ...      7        2170   
2         10000     1.0           0     0  ...      6         770   
3          5000     1.0           0     0  ...      7        1050   
4          8080     1.0           0     0  ...      8        1680   
...         ...     ...         ...   ...  ...    ...         ...   
21608      1131     3.0           0     0  ...      8        1530   
21609      5813     2.0           0     0  ...      8        2310   
21610      1350     2.0           0     0  ...      7        1020   
21611      2388     2.0           0     0  ...      8        1600   
21612      1076     2.0           0     0  ...      7        1020   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0                  0      1955             0    98178  47.5112 -122.257   
1                400      1951          1991    98125  47.7210 -122.319   
2                  0      1933             0    98028  47.7379 -122.233   
3                910      1965             0    98136  47.5208 -122.393   
4                  0      1987             0    98074  47.6168 -122.045   
...              ...       ...           ...      ...      ...      ...   
21608              0      2009             0    98103  47.6993 -122.346   
21609              0      2014             0    98146  47.5107 -122.362   
21610              0      2009             0    98144  47.5944 -122.299   
21611              0      2004             0    98027  47.5345 -122.069   
21612              0      2008             0    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15  
0               1340        5650  
1               1690        7639  
2               2720        8062  
3               1360        5000  
4               1800        7503  
...              ...         ...  
21608           1530        1509  
21609           1830        7200  
21610           1020        2007  
21611           1410        1287  
21612           1020        1357  

[21613 rows x 21 columns]

In [4]:
df1=pd.DataFrame(data=df,columns=('sqft_living','bedrooms','sqft_lot','floors','grade','sqft_above','sqft_basement','lat','sqft_living15','sqft_lot15','price'))
df1         

sqft_living  bedrooms  sqft_lot  floors  grade  sqft_above  \
0             1180         3      5650     1.0      7        1180   
1             2570         3      7242     2.0      7        2170   
2              770         2     10000     1.0      6         770   
3             1960         4      5000     1.0      7        1050   
4             1680         3      8080     1.0      8        1680   
...            ...       ...       ...     ...    ...         ...   
21608         1530         3      1131     3.0      8        1530   
21609         2310         4      5813     2.0      8        2310   
21610         1020         2      1350     2.0      7        1020   
21611         1600         3      2388     2.0      8        1600   
21612         1020         2      1076     2.0      7        1020   

       sqft_basement      lat  sqft_living15  sqft_lot15   price  
0                  0  47.5112           1340        5650  221900  
1                400  47.7210           1690        7639  538000  
2                  0  47.7379           2720        8062  180000  
3                910  47.5208           1360        5000  604000  
4                  0  47.6168           1800        7503  510000  
...              ...      ...            ...         ...     ...  
21608              0  47.6993           1530        1509  360000  
21609              0  47.5107           1830        7200  400000  
21610              0  47.5944           1020        2007  402101  
21611              0  47.5345           1410        1287  400000  
21612              0  47.5941           1020        1357  325000  

[21613 rows x 11 columns]

In [5]:
x=df1.iloc[:,:-1].values

In [6]:
y=df1.iloc[:,-1].values

In [12]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x1=ss.fit_transform(x)
x1

array([[-0.97983502, -0.39873715, -0.22832133, ..., -0.35257175,
        -0.9433552 , -0.26071541],
       [ 0.53363434, -0.39873715, -0.18988538, ...,  1.16156823,
        -0.43268619, -0.18786773],
       [-1.42625404, -1.47395936, -0.12329847, ...,  1.28353661,
         1.07013975, -0.17237524],
       ...,
       [-1.15404732, -1.47395936, -0.33213703, ...,  0.24788796,
        -1.41025258, -0.39414129],
       [-0.52252773, -0.39873715, -0.30707641, ..., -0.18441416,
        -0.8412214 , -0.42051149],
       [-1.15404732, -1.47395936, -0.33875227, ...,  0.24572284,
        -1.41025258, -0.41794772]])

In [17]:
df2=pd.DataFrame(data=x1,columns=('sqft_living','bedrooms','sqft_lot','floors','grade','sqft_above','sqft_basement','lat','sqft_living15','sqft_lot15'))
df2

sqft_living  bedrooms  sqft_lot    floors     grade  sqft_above  \
0        -0.979835 -0.398737 -0.228321 -0.915427 -0.558836   -0.734708   
1         0.533634 -0.398737 -0.189885  0.936506 -0.558836    0.460841   
2        -1.426254 -1.473959 -0.123298 -0.915427 -1.409587   -1.229834   
3        -0.130550  0.676485 -0.244014 -0.915427 -0.558836   -0.891699   
4        -0.435422 -0.398737 -0.169653 -0.915427  0.291916   -0.130895   
...            ...       ...       ...       ...       ...         ...   
21608    -0.598746 -0.398737 -0.337424  2.788439  0.291916   -0.312039   
21609     0.250539  0.676485 -0.224386  0.936506  0.291916    0.629908   
21610    -1.154047 -1.473959 -0.332137  0.936506 -0.558836   -0.927928   
21611    -0.522528 -0.398737 -0.307076  0.936506  0.291916   -0.227505   
21612    -1.154047 -1.473959 -0.338752  0.936506 -0.558836   -0.927928   

       sqft_basement       lat  sqft_living15  sqft_lot15  
0          -0.658681 -0.352572      -0.943355   -0.260715  
1           0.245141  1.161568      -0.432686   -0.187868  
2          -0.658681  1.283537       1.070140   -0.172375  
3           1.397515 -0.283288      -0.914174   -0.284522  
4          -0.658681  0.409550      -0.272190   -0.192849  
...              ...       ...            ...         ...  
21608      -0.658681  1.004958      -0.666135   -0.412381  
21609      -0.658681 -0.356180      -0.228419   -0.203946  
21610      -0.658681  0.247888      -1.410253   -0.394141  
21611      -0.658681 -0.184414      -0.841221   -0.420511  
21612      -0.658681  0.245723      -1.410253   -0.417948  

[21613 rows x 10 columns]

In [13]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y_train,y_test=train_test_split(x1,y,test_size=0.25,random_state=0)

In [14]:
from sklearn.linear_model import SGDRegressor
sgd=SGDRegressor()
sgd.fit(x1_train,y_train)
pred=sgd.predict(x1_test)
pred

array([ 464448.13879604, 1432143.99661532,  488098.89391562, ...,
        786018.36618585,  374493.64474122,  476488.25033703])

In [18]:
new=sgd.predict([[0.12,0.96,0.87,0.67,0.98,0.84,0.56,0.87,0.64,0.76]])
new

array([781911.57892768])

In [15]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
from numpy import sqrt
rmse=sqrt(mean_squared_error(pred,y_test))
rmse

229277.44043099493

In [16]:
from sklearn.metrics import r2_score
r2score=r2_score(pred,y_test)
Accuracy=r2score*100
Accuracy

30.6094506951762