In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('C:\\Users\\krishna\\Downloads\\titanic (1).csv')
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0   7.2500  
1    female  38.0                        1                        0  71.2833  
2    female  26.0                        0                        0   7.9250  
3    female  35.0                        1                        0  53.1000  
4      male  35.0                        0                        0   8.0500  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0  13.0000  
883  female  19.0                        0                        0  30.0000  
884  female   7.0                        1                        2  23.4500  
885    male  26.0                        0                        0  30.0000  
886    male  32.0                        0                        0   7.7500  

[887 rows x 8 columns]

In [3]:
df1=pd.DataFrame(data=df,columns=['Age','Siblings/Spouses Aboard','Parents/Children Aboard','Fare','Pclass','Survived'])
df1

Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  Pclass  \
0    22.0                        1                        0   7.2500       3   
1    38.0                        1                        0  71.2833       1   
2    26.0                        0                        0   7.9250       3   
3    35.0                        1                        0  53.1000       1   
4    35.0                        0                        0   8.0500       3   
..    ...                      ...                      ...      ...     ...   
882  27.0                        0                        0  13.0000       2   
883  19.0                        0                        0  30.0000       1   
884   7.0                        1                        2  23.4500       3   
885  26.0                        0                        0  30.0000       1   
886  32.0                        0                        0   7.7500       3   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
882         0  
883         1  
884         0  
885         1  
886         0  

[887 rows x 6 columns]

In [4]:
x=df1.iloc[:,:-1].values

In [5]:
y=df1.iloc[:,-1].values

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x1_train=ss.fit_transform(x_train)
x1_test=ss.transform(x_test)

In [8]:
from sklearn.svm import SVC
svc=SVC(kernel='rbf')
svc.fit(x1_train,y_train)
pred=svc.predict(x1_test)
pred

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0], dtype=int64)

In [10]:
new=svc.predict([[27,1,2,40,2]])
new

array([0], dtype=int64)

In [12]:
from sklearn.metrics import *

In [13]:
confusion=confusion_matrix(y_test,pred)
confusion

array([[130,  12],
       [ 40,  40]], dtype=int64)

In [14]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.76      0.92      0.83       142
           1       0.77      0.50      0.61        80

    accuracy                           0.77       222
   macro avg       0.77      0.71      0.72       222
weighted avg       0.77      0.77      0.75       222

